### ISSUE TITLE
Strange Console Error

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyPropClient#57] opened 2017-02-21 21:35 UTC
This pops up when running BPClient on my mac from the terminal in the logging that then comes after:

Traceback (most recent call last):
  File "logging/__init__.py", line 861, in emit
  File "logging/__init__.py", line 734, in format
  File "logging/__init__.py", line 465, in format
  File "logging/__init__.py", line 329, in getMessage
ValueError: unsupported format character ' ' (0x20) at index 14
Logged from file SerialSocket.py, line 49
Traceback (most recent call last):
  File "logging/__init__.py", line 861, in emit
  File "logging/__init__.py", line 734, in format
  File "logging/__init__.py", line 465, in format
  File "logging/__init__.py", line 329, in getMessage
ValueError: unsupported format character ' ' (0x20) at index 7
Logged from file BlocklyServer.py, line 57
127.0.0.1 - - [21/Feb/2017:13:30:55] "GET /ports.json HTTP/1.1" 200 30 "http://demo.blockly.parallax.com/blockly/editor/blocklyc.jsp?project=486" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by zfi** [comment] 2017-03-06 18:44
This error is caused by the recent change of the application version number from a floating point number to a string. 

The BlocklyProp browser code was looking for a floating point version number when querying the BlocklyProp Client interface and was no longer finding it. The BlockyProp browser code then set the version to 0.0. This became significant because of another change in the interface between the BlocklyProp browser code and the BlocklyProp client code that permitted the former to send a baud rate for the client.

The client expected to receive a baud rate from the BlocklyProp browser code and failed with the error noted in the original issue.

**Comment by zfi** [comment] 2017-03-06 18:48
Issued PR #59 to address this error.

**Comment by PropGit** [comment] 2017-03-24 14:16
The reported error in this issue was confused with another simultaneous problem that was addressed and solved in PR #59.

The error in the top post was unrelated and not itself fixed by PR #59, it was just coincidental; however, now the error was found to be a bad format string in BlocklyServer.py.

**Comment by PropGit** [comment] 2017-03-24 14:23
This issue is fully solved in PR #85.

**Closed as completed by PropGit** 2017-03-24 14:23 UTC
